name: Build Docker Images

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:

  build:

    name: Build Backend and Frontend

    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v4

      # ==========================
      # BUILD BACKEND
      # ==========================

      - name: Build Backend Image
        uses: docker/build-push-action@v7
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false
          tags: hireflow-backend:test

      # ==========================
      # BUILD FRONTEND
      # ==========================

      - name: Build Frontend Image
        uses: docker/build-push-action@v7
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: false
          build-args: |
            VITE_API_URL=${{ vars.VITE_API_URL }}
          tags: hireflow-frontend:test

      # ==========================
      # SUCCESS
      # ==========================

      - name: Build Summary
        run: |
          echo "======================================"
          echo "       DOCKER BUILD SUCCESSFUL"
          echo "======================================"
          echo ""
          echo "Backend:"
          echo "hireflow-backend:test"
          echo ""
          echo "Frontend:"
          echo "hireflow-frontend:test"
          echo ""
          echo "No images were pushed to GHCR."
          echo "======================================"
